version: '3'

services:

    ireceptor-database:
        image: ireceptor/repository-mongodb:${DATABASE_TAG:-turnkey-v4}
        volumes:
            - ../.mongodb_data:/data/db
        environment:
            MONGO_INITDB_DATABASE: ireceptor

    ireceptor-api:
        depends_on:
            - ireceptor-database
        image: ireceptor/service-php-mongodb:${API_TAG:-turnkey-v4}
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
            DB_SAMPLES_COLLECTION: sample
            DB_SEQUENCES_COLLECTION: sequence
            DB_CELL_COLLECTION: cell
        volumes:
            - ../.config:/config
            - ../.ssl:/etc/apache2/ssl
        ports:
            - ${API_PORT:-80}:80
            - ${API_PORT_HTTPS:-443}:443

    ireceptor-dataloading:
        depends_on:
            - ireceptor-database
        image: ireceptor/dataloading-mongo:${DATALOADING_TAG:-turnkey-v4}
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
        volumes:
            - ../.config:/config
            - ${FILE_FOLDER:-/tmp}:/scratch
