apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ireceptor-dataloading
  name: ireceptor-dataloading
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: boazfr/dataloading-mongo:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
