apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-db
  namespace: frankeb-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
